import initTabNav from './modules/tab-nav.js';
import initAccordionList from './modules/accordion-list.js';
import initSmoothScroll from './modules/smooth-scroll.js';
import initAnimateScroll from './modules/animate-scroll.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdownMenu from './modules/dropdown-menu.js';
import initMobileMenu from './modules/mobile-menu.js';
import initOperating from './modules/operating.js';
import initFetchAnimals from './modules/fetch-animals.js';
import initFetchBitcoin from './modules/fetch-bitcoin.js';

initTabNav();
initAccordionList();
initSmoothScroll();
initAnimateScroll();
initModal();
initTooltip();
initDropdownMenu();
initMobileMenu();
initOperating();
initFetchAnimals();
initFetchBitcoin();
